# ~/.config/alacritty/alacritty.toml

[window]
padding = { x = 6, y = 6 }
dynamic_padding = true
opacity = 1

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
size = 8.0

[cursor]
style = { shape = "Beam", blinking = "Never" }

[terminal.shell]
program = "/bin/zsh"

[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"

[colors.normal]
black   = "#15161E"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#a9b1d6"

[colors.bright]
black   = "#414868"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#c0caf5"

[colors.cursor]
text = "#1a1b26"
cursor = "#c0caf5"

[colors.selection]
text = "#1a1b26"
background = "#33467C"

[terminal]

