require("telescope").load_extension("live_grep_args")

local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>tf', builtin.find_files)
vim.keymap.set('n', '<leader>ts', require("telescope").extensions.live_grep_args.live_grep_args, { noremap = true })
vim.keymap.set('n', '<leader>ta', builtin.lsp_document_symbols)
vim.keymap.set('n', '<leader>tb', builtin.buffers, {})
-- vim.keymap.set('n', '<C-p>', builtin.git_files, {})
-- vim.keymap.set('n', '<leader>pg', builtin.live_grep, {})
--vim.keymap.set('n', '<leader>fg', builtin.live_grep, {})
--vim.keymap.set('n', '<leader>fh', builtin.help_tags, {})
