# See https://www.loraserver.io/lora-app-server/install/config/ for a full
# configuration example and documentation.

[general]
log_level=4
password_hash_iterations=100000

[postgresql]
dsn="postgres://loraserver_as:loraserver_as@postgresql/loraserver_as?sslmode=disable"

automigrate=true


[redis]
url="redis://redis:6379"

[application_server]
id="6d5db27e-4ce2-4b2b-b5d7-91f069397978"


[application_server.integration.mqtt]
uplink_topic_template="application/{{ .ApplicationID }}/node/{{ .DevEUI }}/rx"
downlink_topic_template="application/{{ .ApplicationID }}/node/{{ .DevEUI }}/tx"
join_topic_template="application/{{ .ApplicationID }}/node/{{ .DevEUI }}/join"
ack_topic_template="application/{{ .ApplicationID }}/node/{{ .DevEUI }}/ack"
error_topic_template="application/{{ .ApplicationID }}/node/{{ .DevEUI }}/error"
server="tcp://mosquitto:1883"
username=""
password=""
qos=0
clean_session=true
client_id=""
ca_cert=""
tls_cert=""
tls_key=""

[application_server.api]
public_host="appserver:8001"
bind="0.0.0.0:8001"
ca_cert=""
tls_cert=""
tls_key=""

[application_server.external_api]
bind="0.0.0.0:8080"
jwt_secret="verysecret"
disable_assign_existing_users=false

[join_server]
# ip:port to bind the join-server api interface to
bind="0.0.0.0:8003"
# ca certificate used by the join-server api server
ca_cert=""
# tls certificate used by the join-server api server (optional)
tls_cert=""
# tls key used by the join-server api server (optional)
tls_key=""
# Network-server configuration.
#
# This configuration is only used to migrate from older LoRa App Server.
[network_server]
server="127.0.0.1:8000"


