require "config.basic"
require "config.keymaps"
require "config.plugins"
require('impatient')
require "config.colorscheme"
require "config.lualine"
require "config.cmp"
require "config.lsp"
require "config.telescope"
require "config.treesitter"
require "config.autopairs"
require "config.comments"
require "config.gitsigns"
require "config.nvimtree"
require "config.bufferline"
require "config.lsp.null-ls"
require "config.toggleterm"
require "config.hop"
require "config.indent-blankline"
require "config.fixcursorhold"
require "config.trouble"
require "config.winshift"
require "config.nvim-window"
require "config.harpoon"
require "config.numbers"
require "config.nvim-scrollbar"
require "config.hlslens"
require "config.neogen"
require "config.aerial"
-- require "config.tabnine"
vim.cmd [[set laststatus=3]]
